server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/v1/auth/**

        - id: image-service
          uri: lb://image-service
          predicates:
            - Path=/api/v1/image/**

        - id: main-service
          uri: lb://main-service
          predicates:
            - Path=/api/v1/main/**

        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/v1/queue/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionLocator: INFO
    org.springframework.cloud.gateway: TRACE


